CREATE TABLE User
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Email VARCHAR(200) NOT NULL,
  Username VARCHAR(200) NULL,
  U_Password VARCHAR(200) NOT NULL,
  Verified TINYINT(1) DEFAULT 0 NOT NULL
);
CREATE UNIQUE INDEX User_ID_uindex ON User (ID);
CREATE UNIQUE INDEX User_Email_uindex ON User (Email);

CREATE TABLE User_P
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  UID INT NOT NULL,
  Passphrase VARCHAR(200) NOT NULL,
  Created DATETIME NOT NULL,
  Updated DATETIME
);
CREATE UNIQUE INDEX User_P_ID_uindex ON User_P (ID);

ALTER TABLE User_P
  ADD CONSTRAINT User_P_User_ID_fk
FOREIGN KEY (UID) REFERENCES User (ID);

CREATE TABLE UserCreated
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  UID INT NOT NULL,
  Created DATETIME
);
CREATE UNIQUE INDEX UserCreated_ID_uindex ON UserCreated (ID);


CREATE TABLE UserLogging
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  UID INT NOT NULL,
  LoginTime DATETIME NOT NULL,
  LogoutTime DATETIME DEFAULT NULL
);
CREATE UNIQUE INDEX UserLogging_ID_uindex ON UserLogging (ID);

ALTER TABLE UserLogging
  ADD CONSTRAINT UserLogging_User_ID_fk
FOREIGN KEY (UID) REFERENCES User (ID);

ALTER TABLE UserCreated
  ADD CONSTRAINT UserCreated_User_ID_fk
FOREIGN KEY (UID) REFERENCES User (ID);

ALTER TABLE UserCreated MODIFY Created DATETIME NOT NULL DEFAULT NOW();

CREATE TABLE UserVerify
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  UID INT NOT NULL,
  Token VARCHAR(200) NOT NULL,
  `Delete` DATETIME,
  CONSTRAINT UserVerify_User_ID_fk FOREIGN KEY (UID) REFERENCES User (ID)
);

CREATE UNIQUE INDEX UserVerify_ID_uindex ON UserVerify (ID);
ALTER TABLE UserVerify CHANGE `Delete` Deleted DATETIME;
ALTER TABLE UserVerify ADD Created DATETIME DEFAULT NOW() NOT NULL;
ALTER TABLE UserVerify
  MODIFY COLUMN Deleted DATETIME AFTER Created;